{% set name = "potpourri3d" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/potpourri3d-{{ version }}.tar.gz
  sha256: f211581a478a88609f6deb122782d89439b811d522d6950e210fa617041de00a

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python
    - pip
    - setuptools
    - eigen
    - geometry-central
    - pybind11
  run:
    - python
    - geometry-central
    - numpy
    - scipy

test:
  imports:
    - potpourri3d
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nmwsharp/potpourri3d
  summary: An invigorating blend of 3D geometry tools in Python.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ytausch
